### ISSUE TITLE
963:13: Warning: This declaration shadows an existing declaration. uint round = (farmers[account].round).sub(1); ^--------^ token.sol:458:5: The shadowed declaration is here: uint public round = 1; ^-------------------^ = getting this messag eput up when tryna compile

### ISSUE THREAD

**Issue by euan1111** [ap3town/smart-contract#1]
https://github.com/ap3town/smart-contract/blob/2965bced6d0336c118c40c2db74e0f2e45a53167/ap3town.sol#L962

**Comment by ap3town** [comment]
Have you made any changes? Do you use proper pragma solidity? This warning refers to the 963 line, while you reported issue at the 962 line.
